### ISSUE TITLE
Investigate printf instead of echo

### ISSUE THREAD

**Issue by fidian** [tests-always-included/tomdoc.sh#7]
Instead of using `echo`, try to make a version that uses `printf`.  With that in place, see if it works consistently across all of the different platforms.

Advantages:

* Part of POSIX, so it should be there.
* Eliminates shelling out to echo.
* Can simplify the code within TomDoc.sh.

**Comment by fidian** [comment]
All indications are that this works exactly as I had hoped.  Thanks @mlafeldt for the suggestion!

**Comment by mlafeldt** [comment]
Yeah!
