### ISSUE TITLE
Won't process function names that follow Google bash style guide with :: in name

### ISSUE THREAD

**Issue by phoccer** [tests-always-included/tomdoc.sh#8]
I added the following line of code to the parse_code function, just above the last line of that function, to get tomdoc.sh to process functions that are formatted following the [Google Shell Style Guide](https://google.github.io/styleguide/shell.xml?showone=Function_Names#Function_Names) 

mypackage::myfunction(){
}

-e "s/^${SPACE_RE}(${NAME_RE}::${NAME_RE})().*$/\1()/p" \

**Comment by fidian** [comment]
I think we should change NAME_RE instead.  Bash basically says that a function name can start with one set of characters followed by as many secondary set of characters.  I did a scan of characters and it looks like these are the only values that are not allowed.  Now I just have to update NAME_RE.

```
00 null
01 start of heading
09 \t horizontal tab
0a \n newline
20 space
22 "
23 # ----- can be used as secondary
24 $
26 &
27 '
28 (
29 )
2d - ----- can be used as secondary character
3b ;
3c <
3d = ----- can be leading character
3e >
5b [ ----- can be leading character
5c \ backslash
60 `
7c |
7f delete - can be used as secondary character
```

**Comment by phoccer** [comment]
Ah yes, even cleaner. For now I've simply change NAME_RE as follows

NAME_RE='[a-zA-Z_][a-zA-Z0-9_:]*'

**Comment by fidian** [comment]
For reference, the shell script I used to generate the list of allowed characters is here:

```
#!/usr/bin/env bash

(
    for DEC in {0..1114111}; do
        (
            printf -v HEX "%x" $DEC

            while [[ ${#HEX} -lt 8 ]]; do
                HEX="0${HEX}"
            done

            printf -v C "\U$HEX"

            # Secondary character
            # eval "TEST_${HEX}_${C}_OK() { echo $HEX OK; }" > /dev/null 2>&1
            # set | grep -q "^TEST_${HEX}_._OK "

            # Leading character
            eval "${C}_TEST_${HEX}_OK() { echo $HEX OK; }" > /dev/null 2>&1
            set | grep -q "^._TEST_${HEX}_OK "

            if [[ $? -ne 0 ]]; then
                echo "INVALID: ${HEX}"
            fi
        )
    done
)
```

A similar one was used to generate lines and test them against the sed pattern I've updated.

**Comment by fidian** [comment]
I've fixed the patterns to include the characters expected.  After that I had to fix the escaping so it would work on Mac OS X and it's built-in version of sed.  Finally, I separated out the patterns for function names and variable names.  All of the tests pass and you should be able to use colons (and many other symbols) in your function names without any hiccups.  If you have any problems whatsoever, please reopen this issue or create a new one.
